# version: "3.8"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: "tunnel --no-autoupdate run --token $CF_TUNNEL_TOKEN"
    volumes:
      - ./cloudflared:/etc/cloudflared
    environment:
      - CF_TUNNEL_TOKEN
    restart: unless-stopped
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
  rod:
    image: ghcr.io/go-rod/rod
    ports:
      - 7317:7317
  preview:
    container_name: preview
    depends_on:
      - redis
      - rod
    build:
      context: .
    environment:
      - PORT=7777
      - LAUNCHER_URL=ws://rod:7317
      - ASSETS_PATH=/assets/assets
      - REDIS_URL=redis:6379
      - PREVIEW_URL=http://preview:7777
      - PROXY_TO
      - AUTH_KEY
      - ASSETS_PAT_TOKEN
    ports:
      - 7777:7777
    restart: unless-stopped